repos:
  - repo: local
    hooks:
    - id: clang-format
      name: clang-format
      description: clang-format your C, C++, or C# code
      entry: clang-format
      args: [-style=file, -i]
      language: python
      types_or: [c++, c, cuda]