[build-system]
requires = ["scikit-build-core", "setuptools", "tomli"]
build-backend = "scikit_build_core.setuptools.build_meta"

[project]
name = "lzcomplexity"
version = "0.9.9"
description = "LempelZiv-76 complexity engine. Suited for complexity analysis of time series."
authors = [
    { name = "Efren Aragon", email = "efrenaragon96@gmail.com" }
]
license = { file = "LICENSE" }
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.8"
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Programming Language :: Python :: 3",
    "Programming Language :: C++",
    "Topic :: Software Development :: Libraries",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Information Analysis"
]

[tool.build]
wheel-tag-override = true

[tool.wheel]
expand-macos-universal-tags = true

[tool.setuptools.packages.find]
where = ["python/src"]

[tool.setuptools.package-data]
"*" = ["*.so", "*.pyd", "*.dll", "*.dylib"]

[tool.setuptools.exclude-package-data]
"*" = ["*.pyc", "__pycache__", "*.egg-info"]

[tool.scikit-build]
cmake.version = ">=3.5"
cmake.verbose = true
cmake.build-type = "Release"
cmake.args = ["-DLZ_ONLY_CORE=ON", "-DBUILD_PYTHON=ON", "-GUnix Makefiles", "-DFIXED_VERSION=3.12", "-DFIXED_PYTHON=ON", "-DCMAKE_VERBOSE_MAKEFILE=ON"]
logging.level = "INFO"
wheel.expand-macos-universal-tags = true
# wheel.py-api = ["cp39", "cp310", "cp311", "cp312"]

[tool.scikit-build.cmake.define]
# LZ_ONLY_CORE = true
# BUILD_PYTHON = true
