
INCLUDE (FindPackageHandleStandardArgs)

FIND_PATH (LZ_CORE_DIR
  NAMES include/lz/lz.h
  PATHS ENV PATH
        # /opt/homebrew/Cellar/gcc/13.2.0/include/
  DOC "LZCore root directory")

FIND_PATH (LZ_CORE_INCLUDE_DIR
  NAMES lz/lz.h
  HINTS ${LZ_CORE_DIR}
  PATH_SUFFIXES include
  DOC "LZCore include directory")


IF (MSVC15)
    SET (_LZ_COMPILER vc14)
ELSEIF (MSVC14)
    SET (_LZ_COMPILER vc14)
ELSEIF (MSVC12)
    SET (_LZ_COMPILER vc12)
ELSEIF (MSVC11)
    SET (_LZ_COMPILER vc11)
ELSEIF (MSVC10)
    SET (_LZ_COMPILER vc10)
ELSEIF (MSVC90)
    SET (_LZ_COMPILER vc9)
ELSEIF (MSVC80)
    SET (_LZ_COMPILER vc8)
ELSEIF (WIN32)
    SET (_LZ_COMPILER vc_mt)
ENDIF (MSVC15)

IF (CMAKE_SIZEOF_VOID_P EQUAL 8)
    SET (_LZ_POSSIBLE_LIB_SUFFIXES lib/intel64/${_LZ_COMPILER})
    SET (_LZ_POSSIBLE_BIN_SUFFIXES bin/intel64/${_LZ_COMPILER})
ELSE (CMAKE_SIZEOF_VOID_P EQUAL 8)
    SET (_LZ_POSSIBLE_LIB_SUFFIXES lib/ia32/${_LZ_COMPILER})
    SET (_LZ_POSSIBLE_BIN_SUFFIXES bin/ia32/${_LZ_COMPILER})
ENDIF (CMAKE_SIZEOF_VOID_P EQUAL 8)

LIST (APPEND _LZ_POSSIBLE_LIB_SUFFIXES lib)

FIND_LIBRARY (LZ_LIBRARY_RELEASE
  NAMES LZCore
  HINTS ${LZ_CORE_DIR}
  PATH_SUFFIXES ${_LZ_POSSIBLE_LIB_SUFFIXES}
  DOC "LZCore release library")

FIND_LIBRARY (LZ_LIBRARY_DEBUG
  NAMES LZCore_dbg
  HINTS ${LZ_ROOT_DIR}
  PATH_SUFFIXES ${_LZ_POSSIBLE_LIB_SUFFIXES}
  DOC "LZCore debug library")

IF (LZ_LIBRARY_RELEASE AND LZ_LIBRARY_DEBUG)
    IF (NOT LZ_CORE_LIB)
        SET (LZ_CORE_LIB optimized ${LZ_LIBRARY_RELEASE} debug ${LZ_LIBRARY_DEBUG}
          CACHE STRING "LZ library" FORCE)
    ENDIF (NOT LZ_CORE_LIB)
ELSEIF (LZ_LIBRARY_RELEASE)
    IF (NOT LZ_CORE_LIB)
        SET (LZ_CORE_LIB ${LZ_LIBRARY_RELEASE} CACHE STRING "LZ library" FORCE)
    ENDIF (NOT LZ_CORE_LIB)
ENDIF (LZ_LIBRARY_RELEASE AND LZ_LIBRARY_DEBUG)

message(STATUS "LZCore dirs found")
message(STATUS "Root dir: ${LZ_CORE_DIR}")
message(STATUS "Lib dir: ${LZ_CORE_LIB}")
message(STATUS "Include dir: ${LZ_CORE_INCLUDE_DIR}")

IF(LZ_CORE_DIR AND LZ_CORE_INCLUDE_DIR AND LZ_CORE_LIB)
  FIND_PACKAGE_HANDLE_STANDARD_ARGS (LZCore REQUIRED_VARS LZ_CORE_DIR
      LZ_CORE_INCLUDE_DIR LZ_CORE_LIB HANDLE_COMPONENTS)
ELSE()
  SET(LZCore_FOUND FALSE)
ENDIF()