if(TARGET lzcore)
    message(STATUS "lzcore: ${lzcore_FOUND} and Lib: ${lzcore} with include: ${lzcore_INCLUDE_DIR}")
    return()
endif()

INCLUDE (FindPackageHandleStandardArgs)

FIND_PATH (LZ_CORE_DIR
  NAMES include/lz/lz.h
  PATHS ENV PATH
        # /opt/homebrew/Cellar/gcc/13.2.0/include/
  DOC "lzcore root directory")

FIND_PATH (lzcore_INCLUDE_DIR
  NAMES lz/lz.h
  HINTS ${LZ_CORE_DIR}
  PATH_SUFFIXES include
  DOC "lzcore include directory")


IF (MSVC15)
    SET (_LZ_COMPILER vc14)
ELSEIF (MSVC14)
    SET (_LZ_COMPILER vc14)
ELSEIF (MSVC12)
    SET (_LZ_COMPILER vc12)
ELSEIF (MSVC11)
    SET (_LZ_COMPILER vc11)
ELSEIF (MSVC10)
    SET (_LZ_COMPILER vc10)
ELSEIF (MSVC90)
    SET (_LZ_COMPILER vc9)
ELSEIF (MSVC80)
    SET (_LZ_COMPILER vc8)
ELSEIF (WIN32)
    SET (_LZ_COMPILER vc_mt)
ENDIF (MSVC15)

IF (CMAKE_SIZEOF_VOID_P EQUAL 8)
    SET (_LZ_POSSIBLE_LIB_SUFFIXES lib/intel64/${_LZ_COMPILER})
    SET (_LZ_POSSIBLE_BIN_SUFFIXES bin/intel64/${_LZ_COMPILER})
ELSE (CMAKE_SIZEOF_VOID_P EQUAL 8)
    SET (_LZ_POSSIBLE_LIB_SUFFIXES lib/ia32/${_LZ_COMPILER})
    SET (_LZ_POSSIBLE_BIN_SUFFIXES bin/ia32/${_LZ_COMPILER})
ENDIF (CMAKE_SIZEOF_VOID_P EQUAL 8)

LIST (APPEND _LZ_POSSIBLE_LIB_SUFFIXES lib)

FIND_LIBRARY (LZ_LIBRARY_RELEASE
  NAMES lzcore
  HINTS ${LZ_CORE_DIR}
  PATH_SUFFIXES ${_LZ_POSSIBLE_LIB_SUFFIXES}
  DOC "lzcore release library")

FIND_LIBRARY (LZ_LIBRARY_DEBUG
  NAMES lzcore_dbg
  HINTS ${LZ_ROOT_DIR}
  PATH_SUFFIXES ${_LZ_POSSIBLE_LIB_SUFFIXES}
  DOC "lzcore debug library")

IF (LZ_LIBRARY_RELEASE AND LZ_LIBRARY_DEBUG)
    IF (NOT lzcore_LIB)
        SET (lzcore_LIB optimized ${LZ_LIBRARY_RELEASE} debug ${LZ_LIBRARY_DEBUG}
          CACHE STRING "LZ library" FORCE)
    ENDIF (NOT lzcore_LIB)
ELSEIF (LZ_LIBRARY_RELEASE)
    IF (NOT lzcore_LIB)
        SET (lzcore_LIB ${LZ_LIBRARY_RELEASE} CACHE STRING "LZ library" FORCE)
    ENDIF (NOT lzcore_LIB)
ENDIF (LZ_LIBRARY_RELEASE AND LZ_LIBRARY_DEBUG)

message(STATUS "lzcore dirs found")
message(STATUS "Root dir: ${LZ_CORE_DIR}")
message(STATUS "Lib dir: ${lzcore_LIB}")
message(STATUS "Include dir: ${lzcore_INCLUDE_DIR}")

IF(LZ_CORE_DIR AND lzcore_INCLUDE_DIR AND lzcore_LIB)
  FIND_PACKAGE_HANDLE_STANDARD_ARGS (lzcore REQUIRED_VARS LZ_CORE_DIR
      lzcore_INCLUDE_DIR lzcore_LIB HANDLE_COMPONENTS)
ELSE()
  SET(lzcore_FOUND FALSE)
ENDIF()