# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: CMake on multiple platforms

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  # codespell:
  #   runs-on: [ubuntu-20.04]
  #   timeout-minutes: 10
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Run scan
  #       run: |
  #         sudo apt update && sudo apt install -y codespell
  #         ${GITHUB_WORKSPACE}/.github/scripts/codespell.sh `pwd`

  build:
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        runs-on: [ubuntu-20.04, macos-latest, windows-latest]
        arch: [x64]
        cxx: [g++, clang++]
        std: [20]
        cmake: ["3.5"]

        include:
          - runs-on: ubuntu-20.04
            arch: x64
            cxx: g++
            std: 20
            cmake: "3.5"

          - runs-on: ubuntu-20.04
            arch: x64
            cxx: g++-10
            cmake: "3.6"

          - runs-on: macos-latest
            arch: x64
            cxx: clang++
            std: 20
            cmake: "3.7"

          - runs-on: windows-2019
            arch: x64 # x86 compilers seem to be missing on 2019 image
            cxx: cl
            std: 20
            cmake: "3.5"

    name: CMake ${{ matrix.cmake }} • ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}

    steps:
      - uses: actions/checkout@v4

      # An action for adding a specific version of CMake:
      #   https://github.com/jwlawson/actions-setup-cmake
      - name: Setup CMake ${{ matrix.cmake }}
        uses: jwlawson/actions-setup-cmake@v1.14
        with:
          cmake-version: ${{ matrix.cmake }}

      # - name: Install TBB
      #   shell: bash
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get -qq install libtbb-dev

      - name: Configure
        shell: bash
        run: |
          mkdir build && cd build
          cmake -DCMAKE_CXX_COMPILER=${{ matrix.cxx }} -DCMAKE_CXX_STANDARD=${{ matrix.std }} \
                -DCMAKE_BUILD_TYPE=Release -Dasan=OFF -Dbinding_python=OFF -Dbuiltin_tbb=OFF ..

      - name: Build
        run: |
          cd build
          cmake --build . --config Release
