# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: CMake on multiple platforms

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  # codespell:
  #   runs-on: [ubuntu-20.04]
  #   timeout-minutes: 10
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Run scan
  #       run: |
  #         sudo apt update && sudo apt install -y codespell
  #         ${GITHUB_WORKSPACE}/.github/scripts/codespell.sh `pwd`

  build:
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-22.04, ubuntu-20.04, macos-latest]
        build_type: ["Release", "Debug"]
        cxx: ["g++", "clang++"]

    name: • ${{ matrix.runs-on }} • ${{ matrix.cxx }} •
    runs-on: ${{ matrix.runs-on }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: lukka/get-cmake@latest

      # - name: Install TBB
      #   shell: bash
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get -qq install libtbb-dev

      - name: Patch TBB submodule
        run: patch -p0 -i patches/tbb.patch

      - name: Configure cmake
        env:
          CXX: ${{ matrix.cxx }}
        run: >
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -Dasan=OFF -Dbinding_python=OFF -Dbuiltin_tbb=ON ..

      - name: Build
        run: >
          cd build
          cmake --build . --config ${{ matrix.build_type }}

  msvc:
    name: • ${{ matrix.os }} • ${{ matrix.build_type }} • ${{ matrix.msvc }} •
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: powershell
    strategy:
      fail-fast: false
      matrix:
        msvc:
          - VS-16-2019
          - VS-17-2022
        arch:
          - x64
        build_type:
          - Debug
          - Release
        include:
          - msvc: VS-16-2019
            os: windows-2019
            generator: "Visual Studio 16 2019"
          - msvc: VS-17-2022
            os: windows-2022
            generator: "Visual Studio 17 2022"

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: lukka/get-cmake@latest

      - name: Configure cmake
        run: >
          mkdir build && cd build
          cmake -G "${{ matrix.generator }}" -A ${{ matrix.arch }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -Dasan=OFF -Dbinding_python=OFF -Dbuiltin_tbb=ON ..

      - name: Build
        run: >
          cd build
          cmake --build . --config ${{ matrix.build_type }}
