# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: CMake on multiple platforms for lzcomplexity library

on:
  push:
    # branches: ["main"]
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-linux:
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        include:
          - runs-on: ubuntu-24.04
            platform: ubuntu_24.04
            build_type: "Release"
            cxx: g++
            cc: gcc
            builtinTbb: ON
          - runs-on: ubuntu-22.04
            platform: ubuntu_22.04
            build_type: "Release"
            cxx: g++
            cc: gcc
            builtinTbb: ON

    name: • ${{ matrix.runs-on }} • ${{ matrix.cxx }} • builtinTbb-${{ matrix.builtinTbb }} •
    runs-on: ${{ matrix.runs-on }}

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true

      - name: Set reusable strings
        id: build_path
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - name: Install TBB
        if: matrix.builtinTbb == 'OFF'
        run: |
          sudo apt-get update
          sudo apt-get -q install libtbb-dev

      - name: Install LLVM and Clang
        if: matrix.cxx == 'clang++'
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "17.0"

      # Ubuntu image have problems with clang and stdlib++, so we need to install a newer version
      # - name: Install newer Clang
      #   if: matrix.cxx == 'clang++'
      #   run: |
      #     wget https://apt.llvm.org/llvm.sh
      #     chmod +x ./llvm.sh
      #     sudo ./llvm.sh 17

      - name: Patch TBB submodule
        run: patch -p0 -f -i patches/tbb.patch

      - name: Configure cmake
        env:
          CXX: ${{ matrix.cxx }}
          CC: ${{ matrix.cc }}
        run: |
          cmake -B ${{ steps.build_path.outputs.build-output-dir }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                -Dasan=OFF -DBUILD_PYTHON=OFF -DLZ_DISTANCE=OFF -DLZ_PARALLEL_BACKEND=TBB -DBUILTIN_TBB=${{matrix.builtinTbb}} \
                -S ${{ github.workspace }}

      - name: Build
        run: |
          cmake --build ${{ steps.build_path.outputs.build-output-dir }} --config ${{ matrix.build_type }} -j$(nproc)
      
      - name: Packaging
        run: |
          cd build
          cpack

      - name: Upload package artifacts
        uses: actions/upload-artifact@v6
        with:
          name: lzcomplexity-${{matrix.runs-on}}-${{matrix.cxx}}-package
          path: ./_packages
          retention-days: 1
      
      - name: Install package into staging dir
        run: |
          cmake --install build --prefix $PWD/stage
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v6
        with:
          name: lzcomplexity-${{matrix.runs-on}}-${{matrix.cxx}}-build
          path: stage/

  deploy-launchpad:
    defaults:
      run:
        shell: bash
    needs: build-linux
    strategy:
      matrix:
        include:
          - runs-on: ubuntu-24.04
            platform: ubuntu-24.04
            distro: noble
            build_type: "Release"
            cxx: g++
            cc: gcc
            builtinTbb: ON
          - runs-on: ubuntu-22.04
            platform: ubuntu-22.04
            distro: jammy
            build_type: "Release"
            cxx: g++
            cc: gcc
            builtinTbb: ON

    name: • Deploy PPA • ${{ matrix.runs-on }} •
    runs-on: ${{ matrix.runs-on }}

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true

      - name: Download build artifacts
        uses: actions/download-artifact@v8
        with:
          name: lzcomplexity-${{matrix.runs-on}}-${{matrix.cxx}}-build
          path: ./build

      - name: Install tools fof upload to PPA
        run: sudo apt-get install -y build-essential gnupg dput devscripts debhelper dh-make cmake

      # Set up GPG key for signing
      - name: Set up GPG key
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_KEY_LANUCHPAD }}
          GPG_KEY_PASSPHRASE: ${{ secrets.GPG_KEY_PASSPHRASE }}
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
        run: |
          # Import GPG key with proper formatting
          # Save key to a file to preserve formatting
          echo "$GPG_PRIVATE_KEY" > private.key
          
          # Import both public and private parts
          gpg --import --batch --no-tty private.key
          rm -f private.key

          # echo "$GPG_KEY_PASSPHRASE" | gpg --passphrase-fd 0 --export-secret-key -a > /dev/null 2>&1 || true
          
          # Configure GPG for automated signing
          echo "allow-loopback-pinentry" >> ~/.gnupg/gpg-agent.conf
          echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf

          # Restart GPG agent
          gpgconf --kill gpg-agent
          gpgconf --launch gpg-agent
          sleep 2

          # Verify the key is imported
          gpg --list-secret-keys

          echo "test" | gpg --clearsign --batch --yes --pinentry-mode loopback \
            --passphrase "$GPG_KEY_PASSPHRASE" -u "$GPG_KEY_ID" -o /dev/null
          echo "✅ Signing test passed"

      # Configure dput config file
      # - name: Configure dput for PPA upload
      #   run: |
      #     cat > ~/.dput.cf << EOF
      #     [your-ppa]
      #     fqdn = ppa.launchpad.net
      #     method = sftp
      #     login = ${{ secrets.LAUNCHPAD_USERNAME }}
      #     incoming = ~${{ secrets.LAUNCHPAD_USERNAME }}/ubuntu/${{ secrets.LAUNCHPAD_PPA }}/
      #     EOF

      - name: Configure git for Launchpad
        run: |
          git config --global user.name "Efren Aragon"
          git config --global user.email "${{ secrets.LAUNCHPAD_EMAIL }}"
          git config --global user.signingkey "${{ secrets.GPG_KEY_ID }}"
          git config --global commit.gpgsign true

      - name: Build Debian source package
        env:
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
          GPG_KEY_PASSPHRASE: ${{ secrets.GPG_KEY_PASSPHRASE }}
          VERSION: 0.9.8
          DEBFULLNAME: Efren Aragon
          DEBEMAIL: ${{ secrets.LAUNCHPAD_EMAIL }}
        run: |
          # Create .orig/tar.gz with sources files
          if [ ! -f lzcomplexity_0.9.8.orig.tar.gz ]; then
            tar -czf lzcomplexity_0.9.8.orig.tar.gz ./build
          fi

          # If your project already has a debian directory, copy it
          if [ -d ${{ github.workspace }}/config/lzcomplexity_debian ]; then
            mkdir -p build/debian
            cp -r ${{ github.workspace }}/config/lzcomplexity_debian/* build/debian/
            cp -r build/* ./
            cd build/
          else
            # Create basic debian directory if it doesn't exist
            cd build/
            dh_make -y --single --createorig -p lzcomplexity_${VERSION} -e ${DEBEMAIL}
            # Clean up unnecessary files
            rm -f debian/*.ex debian/*.EX debian/README.*
          fi

          # dch --create \  
          #     --package lzcomplexity \
          #     --newversion ${VERSION}-1~${{ matrix.distro }} \
          #     --distribution ${{ matrix.distro }} \
          #     --no-editor \
          #     "Automatic release for ${{ matrix.distro }}."
          
          echo "$GPG_KEY_PASSPHRASE" | debuild -S -sa \
            -p"gpg --batch --yes --pinentry-mode loopback --passphrase-fd 0" \
            -k"$GPG_KEY_ID"

          # dpkg-buildpackage -S -sa -uc -us   # build without signing
          # debsign -p"gpg --batch --yes --pinentry-mode loopback \
          #  --passphrase-file <(echo "$GPG_KEY_PASSPHRASE")" -k"$GPG_KEY_ID" ../*.changes

          ls -al ./
          ls -al ../

          # Validate source changes
          # cd ${{ github.workspace }}
          # gpg --verify lzcomplexity_${VERSION}-1_source.changes

      - name: Upload to PPA
        env:
          LAUNCHPAD_PPA: ${{ secrets.LAUNCHPAD_PPA }}
          VERSION: 0.9.8
          DISTRO: $(lsb_release -cs)
        run: |
          dput ppa:${LAUNCHPAD_PPA} lzcomplexity_*_source.changes

      # - name: Publish to PPA
      #   uses: yuezk/publish-ppa-package@v2
      #   with:
      #     repository: ${{ secrets.LAUNCHPAD_PPA }}
      #     gpg_private_key: ${{ secrets.GPG_KEY_LANUCHPAD }}
      #     gpg_passphrase: ${{ secrets.GPG_KEY_PASSPHRASE }}
      #     tarball: "*.orig.tar.xz"
      #     deb_email: ${{ secrets.LAUNCHPAD_EMAIL }}
      #     deb_fullname: "Efren Aragon"
      #     debian_dir: "debian"
      #     series: ${{ matrix.distro }}

      # Upload .deb package to Launchpad
      # - name: Upload to Launchpad
      #   if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
      #   env:
      #     LAUNCHPAD_USERNAME: ${{ secrets.LAUNCHPAD_USERNAME }}
      #     LAUNCHPAD_EMAIL: ${{ secrets.LAUNCHPAD_EMAIL }}
      #     LAUNCHPAD_PPA: ${{ secrets.LAUNCHPAD_PPA }}
      #     LAUNCHPAD_KEY: ${{ secrets.GPG_KEY_LANUCHPAD }}
      #     VERSION: 0.9.8
      #     DISTRO: $(lsb_release -cs)
      #   run: |
      #     # Extract the built package
      #     # mkdir -p ~/packaging
      #     # cd ~/packaging

      #     # Set up dput configuration
      #     # echo "machine launchpad login ${LAUNCHPAD_USERNAME} ssh_options = -i ~/.ssh/id_ed25519" > ~/.dput.cf

      #     # Uncompress .deb package
      #     ls -al ~/downloaded/
      #     # unzip ~/downloaded/lzcomplexity-${{ matrix.runs-on }}-${{ matrix.cxx }}-package.zip

      #     # Upload package
      #     dput ppa:${LAUNCHPAD_PPA} ~/downloaded/lzcomplexity_${VERSION}_${{ matrix.platform }}_x86_64.deb


  build-mac:
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        include:
          - runs-on: macos-latest
            build_type: "Release"
            cxx: clang++
            cc: clang
            builtinTbb: ON
            # - runs-on: macos-latest
            #   build_type: "Release"
            #   cxx: clang++
            #   cc: clang
            #   builtinTbb: OFF
          # - runs-on: macos-latest-large
          #   build_type: "Release"
          #   cxx: clang++
          #   cc: clang
          #   builtinTbb: ON
            
    name: • ${{ matrix.runs-on }} • ${{ matrix.cxx }} • builtinTbb-${{ matrix.builtinTbb }} •
    runs-on: ${{ matrix.runs-on }}

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true

      - name: Set reusable strings
        id: build_path
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
      
      - name: Install TBB
        if: matrix.builtinTbb == 'OFF'
        run: |
          brew update
          brew install tbb

      - name: Patch TBB submodule
        run: patch -p0 -i patches/tbb.patch

      - name: Configure cmake
        env:
          CXX: ${{ matrix.cxx }}
          CC: ${{ matrix.cc }}
        run: |
          cmake -B ${{ steps.build_path.outputs.build-output-dir }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                -Dasan=OFF -DBUILD_PYTHON=OFF -DLZ_DISTANCE=OFF -DLZ_PARALLEL_BACKEND=TBB -DBUILTIN_TBB=${{matrix.builtinTbb}} \
                -S ${{ github.workspace }}

      - name: Build
        run: |
          cd build
          cmake --build ${{ steps.build_path.outputs.build-output-dir }} --config ${{ matrix.build_type }} -j$(nproc)
      
      - name: Packaging
        run: |
          cd build
          cpack

      - uses: actions/upload-artifact@v6
        with:
          name: lzcomplexity-${{matrix.runs-on}}-${{matrix.cxx}}-package
          path: ${{ github.workspace }}/_packages
          retention-days: 1
      
      - name: Deploy to brew
        run: |
          ls -al


  build-rpm:
    defaults:
      run:
        shell: bash
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - runs-on: ubuntu-latest
            build_type: "Release"
            cxx: g++
            cc: gcc
            builtinTbb: ON

    name: • RPM • ${{ matrix.cxx }} • builtinTbb-${{ matrix.builtinTbb }} •
    runs-on: ${{ matrix.runs-on }}

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true

      - name: Set reusable strings
        id: build_path
        run: |
         echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - name: Patch TBB submodule
        run: patch -p0 -i patches/tbb.patch

      - name: Configure cmake
        env:
          CXX: ${{ matrix.cxx }}
          CC: ${{ matrix.cc }}
        run: |
          cmake -B ${{ steps.build_path.outputs.build-output-dir }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                -Dasan=OFF -DBUILD_PYTHON=OFF -DLZ_DISTANCE=OFF -DLZ_PARALLEL_BACKEND=TBB -DBUILTIN_TBB=${{matrix.builtinTbb}} \
                -S ${{ github.workspace }}
  
      - name: Build
        run: |
          cmake --build ${{ steps.build_path.outputs.build-output-dir }} --config ${{ matrix.build_type }} -j$(nproc)

      - name: Generate RPM package using CPack
        run: |
          cd build
          cpack -G RPM

      - uses: actions/upload-artifact@v6
        with:
          name: lzcomplexity-redhat-${{matrix.cxx}}-package
          path: ${{ github.workspace }}/_packages
          retention-days: 1

  # Windows cmake compile
  # msvc:
  #   name: • ${{ matrix.os }} • ${{ matrix.build_type }} • ${{ matrix.msvc }} •
  #   runs-on: ${{ matrix.os }}
  #   defaults:
  #     run:
  #       shell: powershell
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       msvc:
  #         - VS-16-2019
  #         - VS-17-2022
  #       arch:
  #         - x64
  #       build_type:
  #         # - Debug
  #         - Release
  #       include:
  #         - msvc: VS-16-2019
  #           os: windows-2019
  #           generator: "Visual Studio 16 2019"
  #         - msvc: VS-17-2022
  #           os: windows-2022
  #           generator: "Visual Studio 17 2022"

  #   steps:
  #     - uses: actions/checkout@v5
  #       with:
  #         submodules: true

  #     # - uses: lukka/get-cmake@latest
  #     #   with:
  #     #     useCloudCache: false
  #     #     useLocalCache: true

  #     - name: Configure cmake
  #       run: >
  #         cmake cmake -S . -B _build/ 
  #         -G "${{ matrix.generator }}" -A ${{ matrix.arch }} 
  #         -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} 
  #         -Dasan=OFF -DBUILD_PYTHON=OFF -DBUILTIN_TBB=ON

  #     - name: Build
  #       run: cmake --build _build/ --config ${{ matrix.build_type }}