# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: CMake on multiple platforms for lztools

on:
  push:
    # branches: ["main"]
    tags:
      - 'v*'
  workflow_dispatch:


jobs:
  # codespell:
  #   runs-on: [ubuntu-20.04]
  #   timeout-minutes: 10
  #   steps:
  #     - uses: actions/checkout@v5
  #     - name: Run scan
  #       run: |
  #         sudo apt update && sudo apt install -y codespell
  #         ${GITHUB_WORKSPACE}/.github/scripts/codespell.sh `pwd`

  # format:
  #   runs-on: [ubuntu-latest]
  #   steps:
  #     - uses: actions/checkout@v5
  #     - name: Run clang-format on modules
  #       run: find ./modules -iname *.h -o -iname *.hpp -o -iname *.cpp | xargs clang-format -i

  build-linux:
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        include:
          - runs-on: ubuntu-24.04
            build_type: "Release"
            cxx: g++
            cc: gcc
            builtinTbb: ON
          - runs-on: ubuntu-22.04
            build_type: "Release"
            cxx: g++
            cc: gcc
            builtinTbb: ON
          # - runs-on: ubuntu-20.04
          #   build_type: "Release"
          #   cxx: g++
          #   cc: gcc
          #   builtinTbb: ON
          # - runs-on: ubuntu-22.04
          #   build_type: "Release"
          #   cxx: clang++
          #   cc: clang
          #   builtinTbb: ON
          # - runs-on: ubuntu-22.04
          #   build_type: "Release"
          #   cxx: clang++
          #   cc: clang
          #   builtinTbb: OFF

    name: • ${{ matrix.runs-on }} • ${{ matrix.cxx }} • builtinTbb-${{ matrix.builtinTbb }} •
    runs-on: ${{ matrix.runs-on }}

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true

      # - uses: lukka/get-cmake@latest
      #   with:
      #     useCloudCache: false
      #     useLocalCache: true

      - name: Set reusable strings
        id: build_path
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - name: Install TBB
        if: matrix.builtinTbb == 'OFF'
        run: |
          sudo apt-get update
          sudo apt-get -q install libtbb-dev

      - name: Install LLVM and Clang
        if: matrix.cxx == 'clang++'
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "17.0"

      # Ubuntu image have problems with clang and stdlib++, so we need to install a newer version
      # - name: Install newer Clang
      #   if: matrix.cxx == 'clang++'
      #   run: |
      #     wget https://apt.llvm.org/llvm.sh
      #     chmod +x ./llvm.sh
      #     sudo ./llvm.sh 17

      - name: Patch TBB submodule
        run: patch -p0 -f -i patches/tbb.patch

      - name: Configure cmake
        env:
          CXX: ${{ matrix.cxx }}
          CC: ${{ matrix.cc }}
        run: |
          cmake -B ${{ steps.build_path.outputs.build-output-dir }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                -Dasan=OFF -DBUILD_PYTHON=OFF -DLZ_PARALLEL_BACKEND=TBB -DBUILTIN_TBB=${{matrix.builtinTbb}} \
                -S ${{ github.workspace }}

      - name: Build
        run: |
          cmake --build ${{ steps.build_path.outputs.build-output-dir }} --config ${{ matrix.build_type }}
      
      - name: Packaging
        run: |
          cd build
          cpack

      - uses: actions/upload-artifact@v6
        with:
          name: lztools-${{matrix.runs-on}}-${{matrix.cxx}}-package
          path: ./_packages
          retention-days: 1

  build-mac:
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        include:
          # - runs-on: macos-latest
          #   build_type: "Release"
          #   cxx: g++-13
          #   cc: gcc-13
          #   builtinTbb: ON
          # - runs-on: macos-latest
          #   build_type: "Release"
          #   cxx: g++-13
          #   cc: gcc-13
          #   builtinTbb: OFF
          - runs-on: macos-latest
            build_type: "Release"
            cxx: clang++
            cc: clang
            builtinTbb: ON
            # - runs-on: macos-latest
            #   build_type: "Release"
            #   cxx: clang++
            #   cc: clang
            #   builtinTbb: OFF
          # - runs-on: macos-latest-large
          #   build_type: "Release"
          #   cxx: clang++
          #   cc: clang
          #   builtinTbb: ON
            
    name: • ${{ matrix.runs-on }} • ${{ matrix.cxx }} • builtinTbb-${{ matrix.builtinTbb }} •
    runs-on: ${{ matrix.runs-on }}

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true

      - name: Set reusable strings
        id: build_path
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
      
      - name: Install TBB
        if: matrix.builtinTbb == 'OFF'
        run: |
          brew update
          brew install tbb

      - name: Patch TBB submodule
        run: patch -p0 -i patches/tbb.patch

      - name: Configure cmake
        env:
          CXX: ${{ matrix.cxx }}
          CC: ${{ matrix.cc }}
        run: |
          cmake -B ${{ steps.build_path.outputs.build-output-dir }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                -Dasan=OFF -DBUILD_PYTHON=OFF -DLZ_PARALLEL_BACKEND=TBB -DBUILTIN_TBB=${{matrix.builtinTbb}} \
                -S ${{ github.workspace }}

      - name: Build
        run: |
          cd build
          cmake --build ${{ steps.build_path.outputs.build-output-dir }} --config ${{ matrix.build_type }}
      
      - name: Packaging
        run: |
          cd build
          cpack

      - uses: actions/upload-artifact@v6
        with:
          name: lztools-${{matrix.runs-on}}-${{matrix.cxx}}-package
          path: ./_packages
          retention-days: 1

  build-rpm:
    defaults:
      run:
        shell: bash
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - runs-on: ubuntu-latest
            build_type: "Release"
            cxx: g++
            cc: gcc
            builtinTbb: ON

    name: • RPM • ${{ matrix.cxx }} • builtinTbb-${{ matrix.builtinTbb }} •
    runs-on: ${{ matrix.runs-on }}

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true

      - name: Set reusable strings
        id: build_path
        run: |
         echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - name: Patch TBB submodule
        run: patch -p0 -i patches/tbb.patch

      - name: Configure cmake
        env:
          CXX: ${{ matrix.cxx }}
          CC: ${{ matrix.cc }}
        run: |
          cmake -B ${{ steps.build_path.outputs.build-output-dir }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                -Dasan=OFF -DBUILD_PYTHON=OFF -DLZ_PARALLEL_BACKEND=TBB -DBUILTIN_TBB=${{matrix.builtinTbb}} \
                -S ${{ github.workspace }}
  
      - name: Build
        run: |
          cmake --build ${{ steps.build_path.outputs.build-output-dir }} --config ${{ matrix.build_type }}

      - name: Generate RPM package using CPack
        run: |
          cd build
          cpack -G RPM

      - uses: actions/upload-artifact@v6
        with:
          name: lztools-redhat-${{matrix.cxx}}-package
          path: ./_packages
          retention-days: 1

  # Test red hat compile
  # install-runner:
  #   runs-on: ubuntu-20.04
  #   name: Install runner
  #   steps:
  #     - name: Install self hosted runner into this repository
  #       uses: redhat-actions/openshift-actions-runner-installer@v1
  #       with:
  #         github_pat: ${{ secrets.PAT }}

  # self-hosted-workflow:
  #   # Now that the above job has ensured the runner container exists,
  #   # we can run our workflow inside it.
  #   name: OpenShift Self Hosted Workflow
  #   # Add other labels here if you have to filter by a runner type.
  #   runs-on: [ self-hosted ]
  #   needs: install-runner

  #   steps:
  #     - run: hostname
  #     - run: ls -Al

  # Windows cmake compile
  # msvc:
  #   name: • ${{ matrix.os }} • ${{ matrix.build_type }} • ${{ matrix.msvc }} •
  #   runs-on: ${{ matrix.os }}
  #   defaults:
  #     run:
  #       shell: powershell
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       msvc:
  #         - VS-16-2019
  #         - VS-17-2022
  #       arch:
  #         - x64
  #       build_type:
  #         # - Debug
  #         - Release
  #       include:
  #         - msvc: VS-16-2019
  #           os: windows-2019
  #           generator: "Visual Studio 16 2019"
  #         - msvc: VS-17-2022
  #           os: windows-2022
  #           generator: "Visual Studio 17 2022"

  #   steps:
  #     - uses: actions/checkout@v5
  #       with:
  #         submodules: true

  #     # - uses: lukka/get-cmake@latest
  #     #   with:
  #     #     useCloudCache: false
  #     #     useLocalCache: true

  #     - name: Configure cmake
  #       run: >
  #         cmake cmake -S . -B _build/ 
  #         -G "${{ matrix.generator }}" -A ${{ matrix.arch }} 
  #         -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} 
  #         -Dasan=OFF -DBUILD_PYTHON=OFF -DBUILTIN_TBB=ON

  #     - name: Build
  #       run: cmake --build _build/ --config ${{ matrix.build_type }}