name: Basic build for pull request

on:
  pull_request:
    branches: ["main"]

jobs:
  build-linux:
    defaults:
      run:
        shell: bash
   
    name: • ubuntu-22.04 • g++ •
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set reusable strings
        id: build_path
        run: |
         echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - name: Patch TBB submodule
        run: patch -p0 -f -i patches/tbb.patch
  
      - name: Configure cmake
        env:
          CXX: g++
          CC: gcc
        run: |
          cmake -B ${{ steps.build_path.outputs.build-output-dir }} -DCMAKE_BUILD_TYPE=Release \
                -Dasan=OFF -DBUILD_PYTHON=OFF -DBUILTIN_TBB=ON \
                -S ${{ github.workspace }}

      - name: Build
        run: |
          cmake --build ${{ steps.build_path.outputs.build-output-dir }} --config Release
      
      - name: Packaging
        run: |
          cd build
          cpack

  build-mac:
    defaults:
      run:
        shell: bash
    
    name: • macos-latest • clang++ •
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set reusable strings
        id: build_path
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - name: Patch TBB submodule
        run: patch -p0 -f -i patches/tbb.patch
  
      - name: Configure cmake
        env:
          CXX: clang++
          CC: clang
        run: |
          cmake -B ${{ steps.build_path.outputs.build-output-dir }} -DCMAKE_BUILD_TYPE=Release \
                -Dasan=OFF -DBUILD_PYTHON=OFF -DBUILTIN_TBB=ON \
                -S ${{ github.workspace }}

      - name: Build
        run: |
          cmake --build ${{ steps.build_path.outputs.build-output-dir }} --config Release

      - name: Packaging
        run: |
          cd build
          cpack
  
  build_python:
    defaults:
      run:
        shell: bash
    
    strategy:
      fail-fast: false
      matrix:
        buildplat:
          - [ubuntu-24.04, manylinux_x86_64]
          - [macos-14, macosx_arm64]
        python: 
          - ["cp310", "3.10"]
    
    env:
      name: lzcomplexity-${{ matrix.python }}-${{ matrix.buildplat[0] }}-${{ matrix.buildplat[1] }}

    name: • ${{ matrix.buildplat[0] }}-${{ matrix.buildplat[1] }} • ${{ matrix.python }} •
    runs-on: ${{ matrix.buildplat[0] }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Patch TBB submodule
        run: patch -p0 -i patches/tbb.patch
      
      - name: Setup python version
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      # - name: Install build dependencies
      #   run: python -m pip install -U pip setuptools wheel build twine

      # - name: Build sdist
      #   run: |
      #     python setup.py sdist
      #     echo "SDIST_FILE=$(basename $(find dist -name '*.tar.gz'))" >> $GITHUB_ENV

      # - name: Install cibuildwheel and twine
      #   run: python -m pip install cibuildwheel==2.21.1 twine wheel

      - name: Generate wheel
        uses: pypa/cibuildwheel@d04cacbc9866d432033b1d09142936e6a0e2121a  # v2.23.2
        with:
          package-dir: .
          output-dir: wheelhouse
        env:
          CIBW_BUILD: ${{ matrix.python[0] }}-${{ matrix.buildplat[1] }}
          # CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
          CIBW_BEFORE_ALL: "pip install scikit-build-core"
          CIBW_BUILD_VERBOSITY: 1
          CIBW_AFTER_BUILD: twine check {wheel}
          CIBW_CMAKE_ARGS: >
            -DPython_EXECUTABLE={python} 
            -DPython_INCLUDE_DIR={python_include} 
            -DPython_LIBRARY={python_lib}
            -DLZ_ONLY_CORE=ON 
            -DBUILD_PYTHON=ON 
            -DFIXED_PYTHON=ON 
            -DFIXED_VERSION=${{ matrix.python[1] }}
          CMAKE_ARGS: "-DLZ_ONLY_CORE=ON -DBUILD_PYTHON=ON -DFIXED_PYTHON=ON -DFIXED_VERSION=${{ matrix.python[1] }}"
      
      # - name: Generate wheel
      #   run: |
      #     python -m cibuildwheel --output-dir wheelhouse
      #     ls -al ./wheelhouse/
      #   env:
      #     # CIBW_PRERELEASE_PYTHONS: True
      #     # CIBW_FREE_THREADED_SUPPORT: True
      #     CIBW_BUILD: ${{ matrix.python }}-${{ matrix.buildplat[1] }}
      #     CIBW_BEFORE_BUILD: "python -m pip install -r requirements.txt"
      #     CIBW_AFTER_BUILD: twine check {wheel}

      # - name: Generate wheel
      #   run: |
      #     python -m pip wheel . --wheel-dir ./dist -v
      #     for wheel in ./dist/*.whl; do
      #       twine check "$wheel"
      #     done

      # - name: Fix macOS wheel ARM
      #   if: matrix.buildplat[1] == 'macosx_arm64'
      #   run: |
      #     python -m pip install --upgrade delocate
      #     for wheel in ./dist/*.whl; do
      #       delocate-wheel --require-archs arm64 -w ./wheelhouse -v "$wheel"
      #     done

      # - name: Fix macOS wheel x86_64
      #   if: matrix.buildplat[1] == 'macosx_x86_64'
      #   run: |
      #     python -m pip install --upgrade delocate
      #     for wheel in ./dist/*.whl; do
      #       delocate-wheel --require-archs x86_64 -w ./wheelhouse -v "$wheel"
      #     done

      # - name: Fix Linux wheel
      #   if: matrix.buildplat[1] == 'manylinux_x86_64' || matrix.buildplat[1] == 'musllinux_x86_64'
      #   run: |
      #     python -m pip install auditwheel
      #     for wheel in ./dist/*.whl; do
      #       auditwheel repair --plat manylinux2014_x86_64 -w ./wheelhouse "$wheel"
      #     done
      
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.name }}
          path: ./wheelhouse/*.whl