# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: Build python wheels

on:
  push:
    branches: ["main"]
    # branches: ["python"]

jobs:
  build_python:
    defaults:
      run:
        shell: bash
    
    strategy:
      fail-fast: false
      matrix:
        buildplat:
          - [ubuntu-22.04, manylinux_x86_64]
          - [ubuntu-24.04, manylinux_x86_64]
          - [ubuntu-22.04, musllinux_x86_64]
          - [ubuntu-24.04, musllinux_x86_64]
          - [macos-13, macosx_x86_64]
          - [macos-14, macosx_arm64]
        python: ["cp39", "cp310", "cp311", "cp312"]
        include:
            - buildplat: [ubuntu-22.04, manylinux_x86_64]
              python: "cp37"
            - buildplat: [ubuntu-22.04, musllinux_x86_64]
              python: "cp37"
    
    env:
      name: lzcomplexity-${{ matrix.python }}-${{ matrix.buildplat[0] }}-${{ matrix.buildplat[1] }}

    name: • ${{ matrix.buildplat[0] }}-${{ matrix.buildplat[1] }} • ${{ matrix.python }} •
    runs-on: ${{ matrix.buildplat[0] }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      
      - name: Setup python version
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Patch TBB submodule
        run: patch -p0 -i patches/tbb.patch

      - name: Setup macOS
        if: matrix.buildplat[0] == 'macos-13' || matrix.buildplat[0] == 'macos-14'
        run: |
         CIBW="RUNNER_OS=macOS MACOSX_DEPLOYMENT_TARGET=12.0"
         echo "CIBW_ENVIRONMENT_MACOS=$CIBW" >> "$GITHUB_ENV"  

      - name: Install cibuildwheel and twine
        run: python -m pip install cibuildwheel==2.21.1 twine

      - name: Generate wheel
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_PRERELEASE_PYTHONS: True
          CIBW_FREE_THREADED_SUPPORT: True
          CIBW_BUILD: ${{ matrix.python }}-${{ matrix.buildplat[1] }}

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.name }}
          path: ./wheelhouse/*.whl
     
      - name: Upload distribution to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload ./wheelhouse/*

  #     - uses: mamba-org/setup-micromamba@v1.9.0
  #       with:
  #        init-shell: bash
  #        environment-name: upload-env
  #        post-cleanup: all
  #        create-args: >-
  #           anaconda-client

  #     - name: Upload wheels to Anaconda
  #       shell: bash -el {0}
  #       env:
  #         # Secret variables need to be mapped to environment variables explicitly
  #        #  SCIKIT_LEARN_NIGHTLY_UPLOAD_TOKEN: ${{ secrets.SCIKIT_LEARN_NIGHTLY_UPLOAD_TOKEN }}
  #         LZCOMPLEXITY_UPLOAD_TOKEN: ${{ secrets.LZCOMPLEXITY_UPLOAD_TOKEN }}
  #       # Force a replacement if the remote file already exists
  #       run: |
  #        source tools/upload_wheels.sh
  #        # Set upload vars
  #        set_upload_vars
  #        # Upload wheels to anaconda env
  #        upload_wheels

  # build-sdist:
  #     name: Build distribution
  #     runs-on: ubuntu-latest
  #     permissions:
  #        contents: write  # IMPORTANT: mandatory for making GitHub Releases
  #        id-token: write  # IMPORTANT: mandatory for sigstore
  #     steps:
  #       - uses: actions/checkout@v4
  #         with:
  #           submodules: true

  #       - name: Patch TBB submodule
  #         run: patch -p0 -i patches/tbb.patch

  #       # Used to push the built wheels
  #       - uses: actions/setup-python@v5
  #         with:
  #           python-version: "3.10"

  #       - name: Build sdist
  #         run: |
  #           python -m pip install -U pip build
  #           python -m build --sdist
       
  #       - uses: actions/upload-artifact@v4
  #         with:
  #           name: 'dist'
  #           path: ./dist/*

  #       - uses: conda-incubator/setup-miniconda@v3.0.4
  #         with:
  #           auto-update-conda: true
  #           python-version: "3.10"

  #       - name: Upload sdist
  #         shell: bash -el {0}
  #         env:
  #           LZCOMPLEXITY_UPLOAD_TOKEN: ${{ secrets.LZCOMPLEXITY_UPLOAD_TOKEN }}
  #         run: |
  #           conda install -y anaconda-client
  #           source tools/upload_wheels.sh
  #           # Set upload vars
  #           set_upload_vars
  #           # Upload wheels to anaconda env
  #           upload_wheels